<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Endereco extends \Application\Entity\Endereco implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'codigoEndereco', 'nomeLogradouro', 'tipoLogradouro', 'numero', 'complemento', 'bairro', 'comunidade', 'areaDeRisco', 'distrito', 'cep', 'titular');
        }

        return array('__isInitialized__', 'codigoEndereco', 'nomeLogradouro', 'tipoLogradouro', 'numero', 'complemento', 'bairro', 'comunidade', 'areaDeRisco', 'distrito', 'cep', 'titular');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Endereco $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCodigoEndereco()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCodigoEndereco();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoEndereco', array());

        return parent::getCodigoEndereco();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeLogradouro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeLogradouro', array());

        return parent::getNomeLogradouro();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomeLogradouro($nomeLogradouro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomeLogradouro', array($nomeLogradouro));

        return parent::setNomeLogradouro($nomeLogradouro);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoLogradouro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoLogradouro', array());

        return parent::getTipoLogradouro();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoLogradouro(\Application\Entity\TipoLogradouro $tipoLogradouro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoLogradouro', array($tipoLogradouro));

        return parent::setTipoLogradouro($tipoLogradouro);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', array());

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero($numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', array($numero));

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function getComplemento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComplemento', array());

        return parent::getComplemento();
    }

    /**
     * {@inheritDoc}
     */
    public function setComplemento($complemento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComplemento', array($complemento));

        return parent::setComplemento($complemento);
    }

    /**
     * {@inheritDoc}
     */
    public function getBairro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBairro', array());

        return parent::getBairro();
    }

    /**
     * {@inheritDoc}
     */
    public function setBairro($bairro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBairro', array($bairro));

        return parent::setBairro($bairro);
    }

    /**
     * {@inheritDoc}
     */
    public function getComunidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComunidade', array());

        return parent::getComunidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setComunidade($comunidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComunidade', array($comunidade));

        return parent::setComunidade($comunidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getAreaDeRisco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAreaDeRisco', array());

        return parent::getAreaDeRisco();
    }

    /**
     * {@inheritDoc}
     */
    public function setAreaDeRisco($areaDeRisco)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAreaDeRisco', array($areaDeRisco));

        return parent::setAreaDeRisco($areaDeRisco);
    }

    /**
     * {@inheritDoc}
     */
    public function getDistrito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDistrito', array());

        return parent::getDistrito();
    }

    /**
     * {@inheritDoc}
     */
    public function setDistrito(\Application\Entity\Distrito $distrito)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDistrito', array($distrito));

        return parent::setDistrito($distrito);
    }

    /**
     * {@inheritDoc}
     */
    public function getCep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCep', array());

        return parent::getCep();
    }

    /**
     * {@inheritDoc}
     */
    public function setCep($cep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCep', array($cep));

        return parent::setCep($cep);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitular()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitular', array());

        return parent::getTitular();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitular(\Application\Entity\Titular $titular)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitular', array($titular));

        return parent::setTitular($titular);
    }

}
