<?
/**
 * IEDCMCMV (http://mcmv.duquedecaxias.rj.gov.br)
 *
 * @link      https://github.com/irvingoliveira/iedcmcmv.git para o código-fonte
 * @copyright Copyright (c) 2013 Irving Fernando de Medeiros Oliveira, Guilherme Sousa dos Santos,
 * Eduardo Agusto Costa Bastos, Secretaria Municipal de Controle Interno, Ciência, Tecnologia e Sistemas de Duque de Caxias - RJ 
 * @license   http://www.gnu.org/licenses/gpl.txt GNU General Public Licence Version 3
 * 
 * Este arquivo é parte do programa IEDCMCMV
 *
 * IEDCMCMV é um software livre; você pode redistribuí-lo e/ou 
 * modificá-lo dentro dos termos da Licença Pública Geral GNU como 
 * publicada pela Fundação do Software Livre (FSF); na versão 3 da 
 * Licença.
 *
 * Este programa é distribuído na esperança de que possa ser  útil, 
 * mas SEM NENHUMA GARANTIA; sem uma garantia implícita de ADEQUAÇÃO a qualquer
 * MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
 * Licença Pública Geral GNU para maiores detalhes.
 * 
 * Você deve ter recebido uma cópia da Licença Pública Geral GNU
 * junto com este programa, se não, escreva para a Fundação do Software
 * Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */
?>
<?php echo $this->doctype(); ?>

<html lang="pt_BR">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Prefeitura Municipal de Duque de Caxias - Minha Casa Minha Vida')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('author', 'Irving Fernando de Medeiros Oliveira')
            ->appendName('author', 'Guilherme Sousa dos Santos')
            ->appendName('author', 'Eduardo Augusto Costa Bastos')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendName('keywords', 'Zend Framework 2, zf2, php, minha casa minha vida,
                duque de caxias, caxias, rio de janeiro, rj, prefeitura, municipio, habitação,
                programa do governo, controle interno, ciência, tecnologia, sistemas')
            ->appendHttpEquiv('Content-Language', 'pt-BR')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/960_16_col.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
//                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
//                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
                ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/form/cadastro-form.js')
            ->prependFile($this->basePath() . '/js/validaCpf.js')
            ->prependFile($this->basePath() . '/js/validaData.js')
            ->prependFile($this->basePath() . '/js/validaDataNascimento.js')
            ->prependFile($this->basePath() . '/js/jquery.mask.min.js')
            ->prependFile($this->basePath() . '/js/additional-methods.min.js')
            ->prependFile($this->basePath() . '/js/jquery.validate.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div class="container_16" id="header"></div>
        
        <div class="container_16" id="content">
            <?php echo $this->content; ?>
            
            <br/>
            <div id="footer">
                <div id="text-footer">
                    <p><b>Secretaria Municipal de Planejamento, Habitação e Urbanismo</b></p>
                    <p>Rua Bartolomeu Guimarães, 85 - Jd. Primavera - Duque de Caxias - RJ</p>
                    <p>Cep: 25215-320 - Tel: (21) 2776-0388 - E-mail: smphu@duquedecaxias.rj.gov.br</p>
                    <p>2013 <?(date("Y")!= "2013")?"- ".date("Y"):""?> - Este é um <a href="http://www.gnu.org" target="_blank">software livre</a> e é regido sobre a licença <a href="http://www.gnu.org/licenses/gpl.txt" target="_blank">GPLv3</a>.</p>    
                </div>
            </div>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
