<?php echo $this->doctype(); ?>

<html lang="pt_BR">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Prefeitura Municipal de Duque de Caxias - Minha Casa Minha Vida')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('author', 'Irving Fernando de Medeiros Oliveira')
            ->appendName('author', 'Guilherme Sousa dos Santos')
            ->appendName('author', 'Eduardo Augusto Costa Bastos')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendName('keywords', 'Zend Framework 2, zf2, php, minha casa minha vida,
                duque de caxias, caxias, rio de janeiro, rj, prefeitura, municipio, habitação,
                programa do governo, controle interno, ciência, tecnologia, sistemas')
            ->appendHttpEquiv('Content-Language', 'pt-BR')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/960_16_col.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
//                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
//                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
                ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/form/cadastro-form.js')
            ->prependFile($this->basePath() . '/js/validaCpf.js')
            ->prependFile($this->basePath() . '/js/validaData.js')
            ->prependFile($this->basePath() . '/js/validaDataNascimento.js')
            ->prependFile($this->basePath() . '/js/jquery.mask.min.js')
            ->prependFile($this->basePath() . '/js/additional-methods.min.js')
            ->prependFile($this->basePath() . '/js/jquery.validate.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div class="container_16" id="header"></div>
        
        <div class="container_16" id="content">
            <?php echo $this->content; ?>
            
            <br/>
            <div id="footer">
                <div id="text-footer">
                    <p><b>Secretaria Municipal de Planejamento, Habitação e Urbanismo</b></p>
                    <p>Rua Bartolomeu Guimarães, 85 - Jd. Primavera - Duque de Caxias - RJ</p>
                    <p>Cep: 25215-320 - Tel: (21) 2776-0388 - E-mail: smphu@duquedecaxias.rj.gov.br</p>
                    <p>2013 <?(date("Y")!= "2013")?"- ".date("Y"):""?> - Este é um <a href="http://www.gnu.org" target="_blank">software livre</a> e é regido sobre a licença <a href="http://www.gnu.org/licenses/gpl.txt" target="_blank">GPLv3</a>.</p>    
                </div>
            </div>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
