<?
/**
 * IEDCMCMV (http://mcmv.duquedecaxias.rj.gov.br)
 *
 * @link      https://github.com/irvingoliveira/iedcmcmv.git para o código-fonte
 * @copyright Copyright (c) 2013 Irving Fernando de Medeiros Oliveira, Guilherme Sousa dos Santos,
 * Eduardo Agusto Costa Bastos, Secretaria Municipal de Controle Interno, Ciência, Tecnologia e Sistemas de Duque de Caxias - RJ 
 * @license   http://www.gnu.org/licenses/gpl.txt GNU General Public Licence Version 3
 * 
 * Este arquivo é parte do programa IEDCMCMV
 *
 * IEDCMCMV é um software livre; você pode redistribuí-lo e/ou 
 * modificá-lo dentro dos termos da Licença Pública Geral GNU como 
 * publicada pela Fundação do Software Livre (FSF); na versão 3 da 
 * Licença.
 *
 * Este programa é distribuído na esperança de que possa ser  útil, 
 * mas SEM NENHUMA GARANTIA; sem uma garantia implícita de ADEQUAÇÃO a qualquer
 * MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
 * Licença Pública Geral GNU para maiores detalhes.
 * 
 * Você deve ter recebido uma cópia da Licença Pública Geral GNU
 * junto com este programa, se não, escreva para a Fundação do Software
 * Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */
?>
<?if($this->form):?>
<script>
    function add_dependente() {
        var currentCount = parseInt($('#countDependentes').val());
        var template = $('form > fieldset > span').data('template');
        template = template.replace(/__index__/g, currentCount);

        $('form > fieldset > span').append(template);
        
        currentCount++;
        $('#countDependentes').val(currentCount);
        
        return false;
    }
</script>

<div id="err"></div>

<div id="help"></div>

<div class="jumbotron">
<?
    $form = $this->form;
    $form->prepare();
    
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();    
?>
</div>

<?else:?>
    <div class="messages">
        <?if($this->sucesso == 1):?>
            <p>Seu cadastro foi efetuado com sucesso. Seu número de protocolo é:</p>
            <h1><?=$this->protocolo?></h1>
            <p>Guarde ele com cuidado, pois esta é a comprovação de que você se inscreveu 
            no programa.</p>
            
        <?else:?>    
            <?if($this->excpt):?>
                <p>Ops, parece que ocorreu um erro!<br/> 
                    Tente novamente mais tarde.</p>
                <a href="#" onclick="history.back(1)">Voltar</a>
            <?elseif($this->err_msg):?>
                <h3>Ocorreram alguns erros durante o envio dos dados. 
                <br />Tente novamente.</h2>
                <a href="#" onclick="history.back(1)">Voltar</a>
            <?endif;?>
        <?endif;?>
    </div>
<?endif;?>
