<?=$this->headScript()->prependFile($this->basePath() . '/js/form/cadastro-form.js');?>
<script>
    function add_dependente() {
        var currentCount = parseInt($('#countDependentes').val());
        var template = $('form > fieldset > span').data('template');
        template = template.replace(/__index__/g, currentCount);

        $('form > fieldset > span').append(template);
        
        currentCount++;
        $('#countDependentes').val(currentCount);
        
        return false;
    }
</script>

<div id="err"></div>

<div id="help"></div>

<div class="jumbotron">
<?
    $form = $this->form;
    $form->prepare();
    
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();    
?>
</div>
