<?if($this->form):?>
<script>
    function add_dependente() {
        var currentCount = parseInt($('#countDependentes').val());
        var template = $('form > fieldset > span').data('template');
        template = template.replace(/__index__/g, currentCount);

        $('form > fieldset > span').append(template);
        
        currentCount++;
        $('#countDependentes').val(currentCount);
        
        return false;
    }
</script>

<div id="err"></div>

<div id="help"></div>

<div class="jumbotron">
<?
    $form = $this->form;
    $form->prepare();
    
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();    
?>
</div>

<?else:?>
    <div class="messages">
        <?if($this->sucesso == 1):?>
            <p>Seu cadastro foi efetuado com sucesso. Seu número de protocolo é:</p>
            <h1><?=$this->protocolo?></h1>
            <p>Guarde ele com cuidado, pois esta é a comprovação de que você se inscreveu 
            no programa.</p>
            
        <?else:?>    
            <?if($this->excpt):?>
                <p>Ops, parece que ocorreu um erro!<br/> 
                    Tente novamente mais tarde.</p>
                <a href="#" onclick="history.back(1)">Voltar</a>
            <?elseif($this->err_msg):?>
                <h3>Ocorreram alguns erros durante o envio dos dados. 
                <br />Tente novamente.</h2>
                <a href="#" onclick="history.back(1)">Voltar</a>
            <?endif;?>
        <?endif;?>
    </div>
<?endif;?>
