<script>
$(document).ready(function() {
    $("#termo").change(function(){
        if($(this).prop("checked"))
            $("#submit").removeAttr("disabled","disabled");
        else
            $("#submit").attr("disabled","disabled");
    });
});
</script>

<div class="content-wrapper">
    <h2>Programa Minha Casa Minha Vida – Faixa 01</h2>

<h4>Leia atentamente para saber como ter acesso ao Programa Minha Casa Minha Vida – Faixa 01</h4>

<p>Para participar do Programa Minha Casa Minha Vida – Faixa 1, no município de 
Duque de Caxias, o candidato deve atender as seguintes condições:
<ul>
    <li>Ter acima de 18 anos de idade;</li>
    <li>Ter renda familiar bruta total até R$ 1.600,00;</li>
    <li>Não possuir imóvel próprio;</li>
    <li>Não ter sido beneficiado anteriormente por programas de habitação de 
        interesse social;</li>
    <li>Residir no município de Duque de Caxias.</li>
</ul>

<b>OS CANDIDATOS QUE NÃO ATENDEREM AS EXIGÊNCIAS ACIMA NÃO SERÃO BENEFICIADOS</b>

</p>

<p>Sobre a inscrição no Programa Minha Casa, Minha Vida:

<ul>
    <li>O candidato deverá preencher apenas um cadastro por família, 
        preferencialmente pelo responsável do núcleo familiar, utilizando o formulário 
        online, informando todos os campos solicitados;</li>
    <li>Quem se inscreveu no Programa Minha Casa Minha Vida, no município de 
        Duque de Caxias <b>a partir de agosto de 2013, com a ficha de inscrição 
        numerada com o protocolo, não precisa se inscrever novamente</b>;</li>

    <li>Quem se inscreveu no Programa Minha Casa Minha Vida, <b>antes de agosto 
        de 2013 e não possui número de protocolo, deve atualizar a sua inscrição por 
        meio da inscrição online</b>;</li>

    <li>As inscrições ocorrem periodicamente, em prazos e datas que são divulgados 
        pela Prefeitura de Duque de Caxias;</li>
</p>

<p>Sobre o Contrato com o Agente Financeiro do Programa Minha Casa Minha Vida:

    <li>A família, quando beneficiada pelo Programa Minha Casa Minha Vida, 
        assina um Contrato de financiamento, com prazo de 120 meses, com o 
        Agente Financeiro (Caixa Econômica Federal ou Banco do Brasil);</li>
    <li>Durante a vigência do contrato não é permitido vender, ceder, trocar 
        ou alugar o imóvel, que deve ser destinado, exclusivamente, para fins 
        de moradia do beneficiário e sua família;</li>
    <li>Os beneficiários do PMCMV pagam prestações correspondentes a 5% da 
        renda bruta familiar mensal, durante dez anos. O valor mínimo da 
        prestação é de R$25,00 por mês (valores correspondentes a legislação 
        vigente em agosto de 2013);</li>
    <li>Para quitação do contrato, antecipadamente, o mutuário perde o direito 
        ao subsídio (desconto) que ele recebe mensalmente.</li>
    <li>A partir da assinatura do contrato, o mutuário assume o compromisso de 
        se mudar para o imóvel no prazo máximo de 30 dias.</li>
    <li>As informações constantes no presente termo de adesão referem-se à 
        legislação existente em julho de 2013. Havendo mudança na legislação, 
        os critérios podem ser alterados.</li>
</ul>    

<b>OS CANDIDATOS DEVERÃO ATENDER A TODAS AS EXIGÊNCIAS DOS AGENTES FINANCEIROS.</b>
</p>
<form action="/application/index/cadastro" name="termos" id="termos">
    <input type='checkbox' name="termo" id="termo" class="termo"/> Declaro, sob as penas do Artigo 299 do Código Penal, 
    que as informações que aqui presto são verdadeiras e que aceito as condições 
    para ter acesso ao Programa Minha Casa Minha Vida, Faixa 01, Duque de Caxias, RJ.
    </div>

    <br />

    <input type="submit" name="submit" id="submit" value="Inscreva-se" disabled="disabled"/>
</form>
